# Generated by Django 6.0.1 on 2026-01-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(default='Django, python', max_length=200),
            preserve_default=False,
        ),
    ]
