# Generated by Django 6.0.1 on 2026-01-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
